# Generated by Django 4.2.6 on 2023-10-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_userprofile_role_alter_userprofile_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
