# Generated by Django 4.2.6 on 2023-10-16 17:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0005_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='cron_schedule',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Invalid cron format', regex='^([-/,* 0-9]+ ){4}[-/,* 0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='industry',
            field=models.CharField(blank=True, choices=[('Agriculture', 'Agriculture'), ('Automotive', 'Automotive'), ('Aviation', 'Aviation'), ('Banking', 'Banking'), ('Biotechnology', 'Biotechnology'), ('Chemical', 'Chemical'), ('Construction', 'Construction'), ('Consulting', 'Consulting'), ('Consumer Goods', 'Consumer Goods'), ('Education', 'Education'), ('Energy', 'Energy'), ('Entertainment', 'Entertainment'), ('Finance', 'Finance'), ('Food & Beverage', 'Food & Beverage'), ('Healthcare', 'Healthcare'), ('Hospitality', 'Hospitality'), ('Information Technology', 'Information Technology'), ('Insurance', 'Insurance'), ('Logistics', 'Logistics'), ('Manufacturing', 'Manufacturing'), ('Marketing', 'Marketing'), ('Media', 'Media'), ('Medical Devices', 'Medical Devices'), ('Pharmaceuticals', 'Pharmaceuticals'), ('Real Estate', 'Real Estate'), ('Retail', 'Retail'), ('Services', 'Services'), ('Telecommunications', 'Telecommunications'), ('Transportation', 'Transportation'), ('Utilities', 'Utilities'), ('Other', 'Other')], max_length=200, null=True),
        ),
    ]
