# Generated by Django 4.2.6 on 2023-10-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0006_campaign_cron_schedule_alter_customer_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='cron_schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
