# Generated by Django 4.2.6 on 2023-10-16 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_remove_campaign_cron_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketingmaterial',
            name='material_type',
            field=models.CharField(choices=[('blog', 'Blog'), ('email', 'Email'), ('newsletter', 'Newsletter')], max_length=100),
        ),
        migrations.CreateModel(
            name='MaterialQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='marketing.marketingmaterial')),
            ],
        ),
    ]
