# Generated by Django 4.2.6 on 2023-10-16 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_remove_marketingmaterial_content_campaign_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketingmaterial',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
