# Generated by Django 4.2.6 on 2023-10-16 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0011_marketingmaterial_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialquestion',
            name='campaign',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='material_questions', to='marketing.campaign'),
            preserve_default=False,
        ),
    ]
